/** Centralised route path constants — prevents magic strings across the codebase. */
export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  CONTACT: '/contact',
  LOGIN: '/login',
  SIGNUP: '/signup',
  VERIFY: '/verify',
  RECIPES: '/recipes',
  RECIPE_DETAIL: '/recipes/:id',
  CREATE_RECIPE: '/create-recipe',
  ORDERS: '/orders',
  BREW_METHODS: '/brew-methods',
  INGREDIENTS: '/ingredients',
  ADMIN_DASHBOARD: '/admin-dashboard',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_RECIPE_CATEGORY: '/admin/recipe-category',
  USER_DASHBOARD: '/user-dashboard',
  NOT_FOUND: '*',
};
